FROM ghcr.io/open-webui/pipelines AS builder
FROM node:latest

RUN apt update; apt install -y vim curl wget unzip build-essential python3-dev python3-setuptools python3-wheel cargo

RUN curl -fsSL https://pi.dev/install.sh | sh
RUN pi install git:github.com/deflating/tau

COPY --from=builder /app /app
WORKDIR /app
RUN curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3 - --break-system-packages
RUN python3 -m pip install -U pip --break-system-packages
RUN python3 -m pip install --no-cache-dir -r requirements.txt --break-system-packages

COPY models.json /root/.pi/agent/models.json

VOLUME /root/.pi/agent/sessions

WORKDIR /root

EXPOSE 3001

ENV TAU_MIRROR_PORT=3001
ENV TAU_HOST=0.0.0.0
#ENV TAU_STATIC_DIR
ENV TAU_DISABLED=0
#ENV TAU_USER=""
#ENV TAU_PASS=""

ENTRYPOINT /bin/bash start.sh

