import subprocess
import json
import os
from typing import Generator, List, Union

class Pipeline:
    def __init__(self):
        self.name = "Pi Coding Agent"
        # Adjust this path if 'pi' is not globally available in your environment
        self.pi_binary = "pi" 

    async def on_startup(self):
        print(f"Starting {self.name}...")

    async def on_shutdown(self):
        print(f"Stopping {self.name}...")

    def pipe(self, user_message: str, model_id: str, messages: List[dict], body: dict) -> Union[str, Generator]:
        """
        Spawns the Pi process in RPC mode, sends the user prompt via stdin JSON,
        and streams back the text results.
        """
        try:
            # Spawn Pi subprocess in JSON-RPC mode
            process = subprocess.Popen(
                [self.pi_binary, "--mode", "rpc"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                bufsize=1
            )
            
            # Format the incoming prompt into Pi's expected JSON wire protocol
            rpc_payload = {
                "jsonrpc": "2.0",
                "method": "prompt",
                "params": {
                    "text": user_message,
                    "history": messages[:-1] # Passes conversational context if needed
                },
                "id": 1
            }
            
            # Send the payload to Pi's stdin
            process.stdin.write(json.dumps(rpc_payload) + "\n")
            process.stdin.flush()
            
            # Read line-by-line streaming responses from Pi's stdout
            def stream_response():
                for line in iter(process.stdout.readline, ""):
                    if not line:
                        break
                    try:
                        data = json.loads(line)
                        # Extract the text patch generated by Pi
                        if "result" in data and "text" in data["result"]:
                            yield data["result"]["text"]
                        elif "error" in data:
                            yield f"\n[Pi Error: {data['error']}]"
                    except json.JSONDecodeError:
                        continue
                
                # Cleanup subprocess on conversation turn finish
                process.terminate()

            return stream_response()

        except Exception as e:
            return f"Failed to interface with Pi Coding Agent: {str(e)}"

